---
- name: Установка и настройка ClickHouse
  hosts: clickhouse
  become: true
  roles:
    - role: clickhouse
      tags:
        - clickhouse

- name: Установка и настройка Vector
  hosts: vector
  become: true
  roles:
    - role: vector
      tags:
        - vector

- name: Установка и настройка LightHouse
  hosts: lighthouse
  become: true
  roles:
    - role: lighthouse
      tags:
        - lighthouse
